workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SDK-OAS:
        inputs:
            - location: ../openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/ritza-rzx/ritza/sdk-oas
targets:
    sdk:
        target: typescript
        source: SDK-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ritza-rzx/ritza/sdk-oas-code-samples
            blocking: false
