/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { catsFindOneCat } from "../funcs/catsFindOneCat.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Cats extends ClientSDK {
  /**
   * Get cat
   */
  async findOneCat(
    request: operations.FindOneCatRequest,
    options?: RequestOptions,
  ): Promise<components.Cat> {
    return unwrapAsync(catsFindOneCat(
      this,
      request,
      options,
    ));
  }
}
