/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dogsFindOneDog } from "../funcs/dogsFindOneDog.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Dogs extends ClientSDK {
  /**
   * Get dog
   */
  async findOneDog(
    request: operations.FindOneDogRequest,
    options?: RequestOptions,
  ): Promise<components.Dog> {
    return unwrapAsync(dogsFindOneDog(
      this,
      request,
      options,
    ));
  }
}
