/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsCreate } from "../funcs/petsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Pets extends ClientSDK {
  /**
   * Create pet
   */
  async create(
    request: operations.CreateRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateResponse> {
    return unwrapAsync(petsCreate(
      this,
      request,
      options,
    ));
  }
}
