/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Cats } from "./cats.js";
import { Dogs } from "./dogs.js";
import { Pets } from "./pets.js";

export class SDK extends ClientSDK {
  private _pets?: Pets;
  get pets(): Pets {
    return (this._pets ??= new Pets(this._options));
  }

  private _cats?: Cats;
  get cats(): Cats {
    return (this._cats ??= new Cats(this._options));
  }

  private _dogs?: Dogs;
  get dogs(): Dogs {
    return (this._dogs ??= new Dogs(this._options));
  }
}
